### ISSUE TITLE
Unexpected usage of lower case names for ebapps

### ISSUE THREAD

**Issue by Falkor** [HPC-buildtest/buildtest#11]
I tried to use buildtest and I noticed a few issues: 

```
$> buildtest -s OpenMPI/2.1.1-GCC-6.3.0-2.28
/home/users/login/buildtest/buildtest-configs
Detecting Software:  OpenMPI/2.1.1-GCC-6.3.0-2.28
Writing Log file:  /dev/shm/buildtest/OpenMPI/2.1.1-GCC-6.3.0-2.28/buildtest_21_52_23_05_2018.log
$> cat /dev/shm/buildtest/OpenMPI/2.1.1-GCC-6.3.0-2.28/buildtest_21_52_23_05_2018.log
2018-05-23 21:52:51,746 [main.py:187 -  main() ] - [DEBUG] BUILDTEST_ROOT=/home/users/login/buildtest/buildtest-framework
2018-05-23 21:52:51,746 [main.py:187 -  main() ] - [DEBUG]
2018-05-23 21:52:51,752 [main.py:235 -  main() ] - [DEBUG] Generating Test from EB Application
2018-05-23 21:52:51,752 [main.py:237 -  main() ] - [DEBUG] Software: OpenMPI
2018-05-23 21:52:51,752 [main.py:238 -  main() ] - [DEBUG] Software Version: 2.1.1-GCC-6.3.0-2.28
2018-05-23 21:52:51,752 [main.py:239 -  main() ] - [DEBUG] Toolchain:
2018-05-23 21:52:51,753 [main.py:240 -  main() ] - [DEBUG] Toolchain Version:
2018-05-23 21:52:51,753 [main.py:242 -  main() ] - [DEBUG] Checking if software: OpenMPI/2.1.1-GCC-6.3.0-2.28 exists
2018-05-23 21:52:51,753 [main.py:257 -  main() ] - [DEBUG] Source App Directory: /home/users/login/buildtest/buildtest-configs/ebapps/openmpi
2018-05-23 21:52:51,753 [main.py:258 -  main() ] - [DEBUG] Config Directory: /home/users/login/buildtest/buildtest-configs/ebapps/openmpi/config
2018-05-23 21:52:51,753 [main.py:259 -  main() ] - [DEBUG] Code Directory: /home/users/login/buildtest/buildtest-configs/ebapps/openmpi/code
2018-05-23 21:52:51,753 [binarytest.py:81 - generate_binary_test() ] - [DEBUG] This is a software binary test
2018-05-23 21:52:51,753 [binarytest.py:82 - generate_binary_test() ] - [DEBUG] Processing YAML file: /home/users/login/buildtest/buildtest-configs/ebapps/openmpi/command.yaml
2018-05-23 21:52:51,753 [binarytest.py:98 - generate_binary_test() ] - [ERROR] ('Cannot find command file:/home/users/login/buildtest/buildtest-configs/ebapps/openmpi/command.yamlSkipping binary test for package:', None)
2018-05-23 21:52:51,753 [main.py:273 -  main() ] - [DEBUG] Writing Log file to /dev/shm/login/buildtest/OpenMPI/2.1.1-GCC-6.3.0-2.28/buildtest_21_52_23_05_2018.log
```

The issue is that `${BUILDTEST_CONFIGS_REPO}/ebapps/` (i.e. `/home/users/login/buildtest/buildtest-configs/ebapps`)  holds repositories with names that **are not** put in lower case -- in this case, `OpenMPI/` and not `openmpi/`

Of course, adding the appropriate symlink makes buildtest succeed: 

```
$> cd /home/users/login/buildtest/buildtest-configs/ebapps
$> ln -s OpenMPI openmpi
$> cd -
$> buildtest -s OpenMPI/2.1.1-GCC-6.3.0-2.28
/home/users/login/buildtest/buildtest-configs
Detecting Software:  OpenMPI/2.1.1-GCC-6.3.0-2.28
--------------------------------------------
[STAGE 1]: Building Binary Tests
--------------------------------------------
Detecting Test Type: Software
Processing Binary YAML configuration:  /home/users/login/buildtest/buildtest-configs/ebapps/openmpi/command.yaml

Generating 22 binary tests
Binary Tests are written in /dev/shm/buildtest-tests/ebapp/OpenMPI/2.1.1-GCC-6.3.0-2.28/
Writing Log file:  /dev/shm/buildtest/OpenMPI/2.1.1-GCC-6.3.0-2.28/buildtest_22_02_23_05_2018.log

```

**Comment by Falkor** [comment]
On a minor side (I put them here rather than opening separate issues) : 

1. the option `--check-setup` does no longer exists? 
2. you should probably complete the setup documentation to install the appropriate packages (typically in a virtualenv): 

             pip install pyyaml argcomplete
3. `buildtest -fc` fails:

```
buildtest -fc all
Traceback (most recent call last):
/home/users/login/buildtest/buildtest-configs
  File "/opt/apps/resif/data/production/v0.1-20170602/default/software/lang/Python/2.7.13-foss-2017a/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/apps/resif/data/production/v0.1-20170602/default/software/lang/Python/2.7.13-foss-2017a/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/irisgpfs/users/login/git/hub.com/HPC-buildtest/buildtest-framework/framework/main.py", line 278, in <module>
    main()
  File "/mnt/irisgpfs/users/login/git/hub.com/HPC-buildtest/buildtest-framework/framework/main.py", line 142, in main
    find_all_yaml_configs()
  File "framework/tools/find.py", line 35, in find_all_yaml_configs
    BUILDTEST_CONFIGS_REPO = configs_opts['DEFAULT']['BUILDTEST_CONFIGS_REPO']
NameError: global name 'configs_opts' is not defined
```

4. `buildtest --scantest` raises strange errors and does not seem to use `config.yaml` 
    - the system tests report also some missing package (`powertop`, `chrony` etc...). Not sure which action should be taken in this case.

```
$> buildtest --scantest
[...]
****************************************
*     EB Apps with YAML configs:       *
****************************************

EBAPP            YAML TEST FOUND
----------------------------------------
Java                find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
HDF5                find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
Perl                find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
M4                  find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
Automake            find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
PCRE                find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
bzip2               find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
Python              find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
gettext             find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
CUDA                find: paths must precede expression: config.example.yaml
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
0
[...]
****************************************************
*     System Package with/without YAML configs:    *
****************************************************

Found YAML config for system package:  procps-ng-3.3.10-16.el7.x86_64
Found YAML config for system package:  perl-5.16.3-292.el7.x86_64
Found YAML config for system package:  ruby-2.0.0.648-33.el7_4.x86_64
Could not find YAML config for system package: package powertop is not installed
Could not find YAML config for system package: package chrony is not installed
Found YAML config for system package:  numactl-2.0.9-6.el7_2.x86_64
Could not find YAML config for system package: package ltrace is not installed
Found YAML config for system package:  python-2.7.5-58.el7.x86_64
Found YAML config for system package:  curl-7.29.0-42.el7_4.1.x86_64
Found YAML config for system package:  util-linux-2.23.2-43.el7_4.2.x86_64
Could not find YAML config for system package: package pinfo is not installed
Found YAML config for system package:  coreutils-8.22-18.el7.x86_64
Found YAML config for system package:  time-1.7-45.el7.x86_64
Could not find YAML config for system package: package CentrifyDC-openssh is not installed
Found YAML config for system package:  binutils-2.25.1-32.base.el7_4.2.x86_64
Found YAML config for system package:  systemd-219-42.el7_4.10.x86_64
Could not find YAML config for system package: package diffstat is not installed
Found YAML config for system package:  sed-4.2.2-5.el7.x86_64
Found YAML config for system package:  wget-1.14-15.el7_4.1.x86_64
Found YAML config for system package:  ncurses-5.9-14.20130511.el7_4.x86_64
Found YAML config for system package:  iptables-1.4.21-18.3.el7_4.x86_64
Found YAML config for system package:  file-5.11-33.el7.x86_64
Found YAML config for system package:  hwloc-1.11.2-2.el7.x86_64
Found YAML config for system package:  gcc-4.8.5-16.el7_4.2.x86_64
Found YAML config for system package:  git-1.8.3.1-12.el7_4.x86_64
Found YAML config for system package:  gcc-gfortran-4.8.5-16.el7_4.2.x86_64
Found YAML config for system package:  gcc-c++-4.8.5-16.el7_4.2.x86_64
Found YAML config for system package:  acl-2.2.51-12.el7.x86_64
```

**Comment by shahzebsiddiqui** [comment]
Hi @Falkor so your first issue with lower case name is because I have not made change to master branch. If you use the devel branch https://github.com/HPC-buildtest/buildtest-configs/tree/devel that will solve your issue.

Yes the packages ``pyyaml`` and ``argcomplete`` are needed for buildtest. I will document this thanks for catching this.

Can you please confirm that you are using the buildtest-framework devel branch. 

Also if you would like to join the Slack channel it will be helpful to get in touch with me. Also please post issues related to buildtest-framework at https://github.com/HPC-buildtest/buildtest-framework/issues 

This repo is related to documentation that is found at http://buildtestdocs.readthedocs.io/en/latest/

**Comment by Falkor** [comment]
Upon cloning according to the [documentation](http://buildtestdocs.readthedocs.io/en/latest/Setup.html#installing-buildtest), the default branch is retrieved, thus the `devel` one for the [buildtest-framework](https://github.com/HPC-buildtest/buildtest-framework) repository. And the lower case issue I mentioned still exists.

**Comment by shahzebsiddiqui** [comment]
Okay I have changed the default branch to master for  [buildtest-framework](https://github.com/HPC-buildtest/buildtest-framework).

Could you please sync your branch for buildtest-framework and buildtest-configs to ensure you are up to date. Also please use the master branch going forward. I have the made the change on my end.

```
git fetch origin master
git pull -r origin master
```

The option ``--check-setup`` was removed in version 0.2.0 see https://github.com/HPC-buildtest/buildtest-framework/releases/tag/v0.2.0 

I need to work on the output of ``--scantest`` don't worry about if you system package is not installed it just says buildtest has yaml files but doesn't see that package in your system. 

I sent you an invitation to the slack channel http://hpcbuildtest.slack.com if you want to get in touch and see if I can resolve your issue.

FYI. I am working on getting creating a buildtest python package so you can install this via pip. I will get back to you when that is complete.

**Comment by shahzebsiddiqui** [comment]
Hi @Falkor,

I have not heard back from you on this task. Do you want me to close this issue. If you need assistance I can help you out if you join slack channel.

Mean while I have been working on packaging buildtest into python package to help ease installation. I will have it out soon.
